<template><div><h1 id="小技巧-利用feuture线程池多个线程一起执行" tabindex="-1"><a class="header-anchor" href="#小技巧-利用feuture线程池多个线程一起执行" aria-hidden="true">#</a> 小技巧：利用Feuture线程池多个线程一起执行</h1>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token keyword">private</span> <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">DbjdSyTjVo</span><span class="token punctuation">></span></span> <span class="token function">getZgTjjg</span><span class="token punctuation">(</span><span class="token class-name">SyTjDTO</span> dto<span class="token punctuation">,</span> <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">String</span><span class="token punctuation">></span></span> corpIdList<span class="token punctuation">)</span> <span class="token keyword">throws</span> <span class="token class-name">ExecutionException</span><span class="token punctuation">,</span> <span class="token class-name">InterruptedException</span> <span class="token punctuation">{</span>
        <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">DbjdSyTjVo</span><span class="token punctuation">></span></span> tjjgList<span class="token punctuation">;</span>
        <span class="token comment">// 拿到线程池，两个线程同时进行统计</span>
        <span class="token class-name">ExecutorService</span> executor <span class="token operator">=</span> <span class="token class-name">Executors</span><span class="token punctuation">.</span><span class="token function">newFixedThreadPool</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token class-name">Future</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">List</span><span class="token punctuation">&lt;</span><span class="token class-name">DbjdSyTjVo</span><span class="token punctuation">></span><span class="token punctuation">></span></span> futureA <span class="token operator">=</span> executor<span class="token punctuation">.</span><span class="token function">submit</span><span class="token punctuation">(</span>
                <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-></span> zxjdxxMapper<span class="token punctuation">.</span><span class="token function">listSyZgjdTjA</span><span class="token punctuation">(</span>dto<span class="token punctuation">.</span><span class="token function">getKssj</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> dto<span class="token punctuation">.</span><span class="token function">getJssj</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> corpIdList<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token class-name">Future</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">List</span><span class="token punctuation">&lt;</span><span class="token class-name">DbjdSyTjVo</span><span class="token punctuation">></span><span class="token punctuation">></span></span> futureF <span class="token operator">=</span> executor<span class="token punctuation">.</span><span class="token function">submit</span><span class="token punctuation">(</span>
                <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-></span> zxjdxxMapper<span class="token punctuation">.</span><span class="token function">listSyZgjdTjF</span><span class="token punctuation">(</span>dto<span class="token punctuation">.</span><span class="token function">getKssj</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> dto<span class="token punctuation">.</span><span class="token function">getJssj</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> corpIdList<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// 组装两次的结果</span>
        tjjgList <span class="token operator">=</span> futureA<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        tjjgList<span class="token punctuation">.</span><span class="token function">addAll</span><span class="token punctuation">(</span>futureF<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span> tjjgList<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>futureF.get()会阻塞等待结果的返回</p>
</div></template>


