<template><div><h3 id="调用webservice工具类" tabindex="-1"><a class="header-anchor" href="#调用webservice工具类" aria-hidden="true">#</a> 调用WebService工具类</h3>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token keyword">package</span> <span class="token namespace">com<span class="token punctuation">.</span>thunisoft<span class="token punctuation">.</span>zbxc<span class="token punctuation">.</span>util</span><span class="token punctuation">;</span>

<span class="token keyword">import</span> <span class="token import"><span class="token namespace">lombok<span class="token punctuation">.</span>experimental<span class="token punctuation">.</span></span><span class="token class-name">UtilityClass</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">lombok<span class="token punctuation">.</span>extern<span class="token punctuation">.</span>slf4j<span class="token punctuation">.</span></span><span class="token class-name">Slf4j</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">org<span class="token punctuation">.</span>apache<span class="token punctuation">.</span>commons<span class="token punctuation">.</span>lang3<span class="token punctuation">.</span></span><span class="token class-name">StringUtils</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">org<span class="token punctuation">.</span>apache<span class="token punctuation">.</span>cxf<span class="token punctuation">.</span>endpoint<span class="token punctuation">.</span></span><span class="token class-name">Client</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">org<span class="token punctuation">.</span>apache<span class="token punctuation">.</span>cxf<span class="token punctuation">.</span>jaxws<span class="token punctuation">.</span>endpoint<span class="token punctuation">.</span>dynamic<span class="token punctuation">.</span></span><span class="token class-name">JaxWsDynamicClientFactory</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">org<span class="token punctuation">.</span>apache<span class="token punctuation">.</span>cxf<span class="token punctuation">.</span>transport<span class="token punctuation">.</span>http<span class="token punctuation">.</span></span><span class="token class-name">HTTPConduit</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">org<span class="token punctuation">.</span>apache<span class="token punctuation">.</span>cxf<span class="token punctuation">.</span>transports<span class="token punctuation">.</span>http<span class="token punctuation">.</span>configuration<span class="token punctuation">.</span></span><span class="token class-name">HTTPClientPolicy</span></span><span class="token punctuation">;</span>

<span class="token doc-comment comment">/**
 *
 * StaticInvokeJaxWs
 * <span class="token keyword">@description</span> 连接
 * <span class="token keyword">@author</span> lixiangyang
 * <span class="token keyword">@date</span> 2020/7/30 15:13
 * <span class="token keyword">@version</span> 1.0.0
 */</span>

<span class="token annotation punctuation">@Slf4j</span>
<span class="token annotation punctuation">@UtilityClass</span>
<span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">StaticInvokeJaxWs</span> <span class="token punctuation">{</span>
    <span class="token doc-comment comment">/**
     * 连接超时时间
     */</span>
    <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">final</span>  <span class="token class-name">Long</span> <span class="token constant">WSCONNECTIONTIMEOUT</span> <span class="token operator">=</span> <span class="token number">3</span> <span class="token operator">*</span> <span class="token number">60</span> <span class="token operator">*</span> <span class="token number">100L</span><span class="token punctuation">;</span>

    <span class="token doc-comment comment">/**
     * 响应超时时间
     */</span>
    <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">final</span>  <span class="token class-name">Long</span> <span class="token constant">RECEIVETIMEOUT</span> <span class="token operator">=</span> <span class="token number">5</span> <span class="token operator">*</span> <span class="token number">60</span> <span class="token operator">*</span> <span class="token number">100L</span><span class="token punctuation">;</span>

    <span class="token doc-comment comment">/**
     *
     * StaticInvokeJaxWs
     * <span class="token keyword">@description</span> webservice 方法调用
     * <span class="token keyword">@param</span> <span class="token parameter">wsdl</span>  wsdl地址
     * <span class="token keyword">@param</span> <span class="token parameter">clazz</span> 类对象名
     * <span class="token keyword">@param</span> <span class="token parameter">methodName</span>    方法名称
     * <span class="token keyword">@param</span> <span class="token parameter">params</span>    参数
     * <span class="token keyword">@return</span>  返回值
     * <span class="token keyword">@author</span> huangyi-1
     * <span class="token keyword">@date</span> 2020年6月3日 下午2:17:21
     * <span class="token keyword">@version</span> v1.0
     */</span>
    <span class="token annotation punctuation">@SuppressWarnings</span><span class="token punctuation">(</span><span class="token string">"unchecked"</span><span class="token punctuation">)</span>
    <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token class-name">String</span> <span class="token function">invokeJaxWsNew</span><span class="token punctuation">(</span><span class="token class-name">String</span> wsdl<span class="token punctuation">,</span> <span class="token class-name">String</span> methodName<span class="token punctuation">,</span> <span class="token class-name">Object</span><span class="token punctuation">[</span><span class="token punctuation">]</span> params<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">long</span> start <span class="token operator">=</span> <span class="token class-name">System</span><span class="token punctuation">.</span><span class="token function">currentTimeMillis</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        log<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token string">"webservice被调用,URL:{},method:{},参数:{}"</span> <span class="token punctuation">,</span>wsdl<span class="token punctuation">,</span>methodName<span class="token punctuation">,</span>params<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token class-name">ClassLoader</span> cl <span class="token operator">=</span> <span class="token class-name">Thread</span><span class="token punctuation">.</span><span class="token function">currentThread</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getContextClassLoader</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token class-name">JaxWsDynamicClientFactory</span> dcf <span class="token operator">=</span> <span class="token class-name">JaxWsDynamicClientFactory</span><span class="token punctuation">.</span><span class="token function">newInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">try</span> <span class="token punctuation">(</span><span class="token class-name">Client</span> client <span class="token operator">=</span> dcf<span class="token punctuation">.</span><span class="token function">createClient</span><span class="token punctuation">(</span>wsdl<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token class-name">HTTPConduit</span> http <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token class-name">HTTPConduit</span><span class="token punctuation">)</span> client<span class="token punctuation">.</span><span class="token function">getConduit</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token class-name">HTTPClientPolicy</span> httpClientPolicy <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">HTTPClientPolicy</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            httpClientPolicy<span class="token punctuation">.</span><span class="token function">setConnectionTimeout</span><span class="token punctuation">(</span><span class="token constant">WSCONNECTIONTIMEOUT</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//连接超时</span>

            httpClientPolicy<span class="token punctuation">.</span><span class="token function">setAllowChunking</span><span class="token punctuation">(</span><span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//取消块编码</span>
            httpClientPolicy<span class="token punctuation">.</span><span class="token function">setReceiveTimeout</span><span class="token punctuation">(</span><span class="token constant">RECEIVETIMEOUT</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//响应超时</span>
            http<span class="token punctuation">.</span><span class="token function">setClient</span><span class="token punctuation">(</span>httpClientPolicy<span class="token punctuation">)</span><span class="token punctuation">;</span>

            <span class="token class-name">Object</span><span class="token punctuation">[</span><span class="token punctuation">]</span> objects <span class="token operator">=</span> client<span class="token punctuation">.</span><span class="token function">invoke</span><span class="token punctuation">(</span>methodName<span class="token punctuation">,</span> params<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token class-name">String</span> result <span class="token operator">=</span> objects<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token operator">==</span> <span class="token keyword">null</span> <span class="token operator">?</span> <span class="token class-name">StringUtils</span><span class="token punctuation">.</span><span class="token constant">EMPTY</span> <span class="token operator">:</span> objects<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            log<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token string">"webservice返回结果:{}"</span><span class="token punctuation">,</span> result<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">return</span> result<span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span><span class="token class-name">Exception</span> e<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">RuntimeException</span><span class="token punctuation">(</span><span class="token string">"调用webService获取结果出错"</span><span class="token punctuation">,</span> e<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">finally</span> <span class="token punctuation">{</span>
            <span class="token class-name">Thread</span><span class="token punctuation">.</span><span class="token function">currentThread</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">setContextClassLoader</span><span class="token punctuation">(</span>cl<span class="token punctuation">)</span><span class="token punctuation">;</span>
            log<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token string">"【计时】webservice结束 "</span> <span class="token operator">+</span> <span class="token punctuation">(</span><span class="token class-name">System</span><span class="token punctuation">.</span><span class="token function">currentTimeMillis</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-</span> start<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

<span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


